### ISSUE TITLE
Add Font License File

### ISSUE THREAD

**Issue by kokoye2007** [emoosx/beautiful-burmese-type#4]
Its pretty and awesome project.

but if font is OFL or GPL or else ?
just suggestion.

Thanks you so much.

**Comment by khzaw** [comment]
@kokoye2007 Thank you. Most of the fonts from khmertype are under OFL. Google's Noto fonts are under SIL open font. Some are unclear on which license are they using. I have a list of links all unicode standard compliant fonts at https://github.com/khzaw/awesome-myanmar-unicode
